import type { NextPage } from 'next';
import Head from 'next/head';
import { connect } from 'react-redux';
import { Button } from '@material-ui/core';
import uniqid from 'uniqid';
import { addTodo } from '../lib/redux/slices/todo';

const TodoId: NextPage = (props: any) => {
  const { todos, dispatch } = props;

  const onAddTodo = () => {
    dispatch(addTodo({ id: uniqid('id-'), title: 'Hello' }));
  };

  return (
    <div>
      <Head>
        <title>Individual Todo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section>
        <div>
          <Button color='primary' onClick={onAddTodo}>
            Back
          </Button>
        </div>
      </section>
    </div>
  );
};

const mapStateToProps = (state: any) => {
  return {
    todos: state.todo,
  };
};

export default connect(mapStateToProps)(TodoId);
